// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuFHU_NrLglpNR1f9QZFY58-qwDsh08xs',
    appId: '1:955961711743:web:9e23cf2716d4278dd7334a',
    messagingSenderId: '955961711743',
    projectId: 'test-analytics-a6a69',
    authDomain: 'test-analytics-a6a69.firebaseapp.com',
    storageBucket: 'test-analytics-a6a69.appspot.com',
    measurementId: 'G-B65CX2J1H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHug_oeYLdfZe28PHapv_sC1ZKn7mbAjM',
    appId: '1:955961711743:android:29ccdc3706b0e26fd7334a',
    messagingSenderId: '955961711743',
    projectId: 'test-analytics-a6a69',
    storageBucket: 'test-analytics-a6a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAA64fQDx2Sci0W_pPV6cMro39mkvwd18',
    appId: '1:955961711743:ios:e16c9c2094a49b1bd7334a',
    messagingSenderId: '955961711743',
    projectId: 'test-analytics-a6a69',
    storageBucket: 'test-analytics-a6a69.appspot.com',
    iosClientId: '955961711743-ied6jpqo6qfj68j096dum1r4qhif3ka5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pgPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAA64fQDx2Sci0W_pPV6cMro39mkvwd18',
    appId: '1:955961711743:ios:e16c9c2094a49b1bd7334a',
    messagingSenderId: '955961711743',
    projectId: 'test-analytics-a6a69',
    storageBucket: 'test-analytics-a6a69.appspot.com',
    iosClientId: '955961711743-ied6jpqo6qfj68j096dum1r4qhif3ka5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pgPoc',
  );
}
